import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import UserDashboardShell from "./_components/UserDashboardShell";
import LogoutProvider from "./_components/LogoutProvider";
import ThemeProvider from "./_components/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col transition-colors duration-300 dark:bg-gray-950 dark:text-white">
        <ThemeProvider>
          <LogoutProvider>
            <UserDashboardShell>{children}</UserDashboardShell>
          </LogoutProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
